import turtle
boo = turtle.Turtle()
boo.shape("turtle")
scn = turtle.Screen()
oogway = turtle.Turtle()
oogway.shape("turtle")
oogway.turtlesize(.5)
eros = turtle.Turtle()
eros.shape("turtle")
eros.turtlesize(.5)
maturin = turtle.Turtle()
maturin.shape("turtle")
maturin.turtlesize(.5)

boo.turtlesize(.5)
boo.color("green")
boo.begin_fill()
boo.circle(100)
boo.end_fill()
oogway.color("black")
oogway.penup()
oogway.goto(45,115)
oogway.pendown()
oogway.begin_fill()
oogway.circle(17)
oogway.end_fill()
oogway.goto(47,122)
eros.goto(-45,115)
eros.color("black")
eros.begin_fill()
eros.circle(17)
eros.end_fill()
eros.goto(-45,122)

maturin.color("black")
maturin.penup()
maturin.goto(-45,75)
maturin.pendown()
def squigle():
    for i in range(3):
        maturin.forward(6)
        maturin.right(50)
        maturin.forward(5)
        maturin.left(55)
        maturin.forward(5)

squigle()
squigle()
maturin.penup()
maturin.goto(-45,122)

boo.goto(-45,70)

turtle.exitonclick()
